// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6U0oPYCaT_Rb_skZ4nhl-rp-zfOxmN8A',
    appId: '1:26654874398:web:1d9991eb21a109baf9c70f',
    messagingSenderId: '26654874398',
    projectId: 'driftaway-0811',
    authDomain: 'driftaway-0811.firebaseapp.com',
    storageBucket: 'driftaway-0811.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo3dV35Y6TZzTTcmeC8eCdTaqAhT7-jyA',
    appId: '1:26654874398:android:988a68750a84a688f9c70f',
    messagingSenderId: '26654874398',
    projectId: 'driftaway-0811',
    storageBucket: 'driftaway-0811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP60xVn00apoH-Af5D-il0-ZInMG8knpw',
    appId: '1:26654874398:ios:3f215ab9e57f5847f9c70f',
    messagingSenderId: '26654874398',
    projectId: 'driftaway-0811',
    storageBucket: 'driftaway-0811.firebasestorage.app',
    iosBundleId: 'com.example.driftaway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP60xVn00apoH-Af5D-il0-ZInMG8knpw',
    appId: '1:26654874398:ios:3f215ab9e57f5847f9c70f',
    messagingSenderId: '26654874398',
    projectId: 'driftaway-0811',
    storageBucket: 'driftaway-0811.firebasestorage.app',
    iosBundleId: 'com.example.driftaway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6U0oPYCaT_Rb_skZ4nhl-rp-zfOxmN8A',
    appId: '1:26654874398:web:36b7161783990f47f9c70f',
    messagingSenderId: '26654874398',
    projectId: 'driftaway-0811',
    authDomain: 'driftaway-0811.firebaseapp.com',
    storageBucket: 'driftaway-0811.firebasestorage.app',
  );
}
